"""Application-specific GUI drivers.

Each module here holds what is true about one application: its windows, its
forms, its login sequence, and its keyboard shortcuts. The generic machinery
lives one level up.

A driver is paired with a YAML knowledge base beside it, which is the single
source of truth for selectors and is regenerated by discovery tooling rather
than hand-edited.
"""
